# Generated by Django 5.0.4 on 2024-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='institution',
        ),
        migrations.AddField(
            model_name='courses',
            name='institutionId',
            field=models.IntegerField(null=True),
        ),
    ]
