# Generated by Django 5.0.4 on 2024-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255, null=True)),
                ('depot', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(default='pass@123', max_length=255)),
            ],
        ),
    ]
