# Generated by Django 5.0.4 on 2024-04-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='ConcessionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/photo')),
                ('idCard', models.ImageField(null=True, upload_to='images/id')),
                ('aadhar', models.CharField(max_length=12, null=True)),
                ('aadharFront', models.ImageField(null=True, upload_to='images/aadharFront')),
                ('aadharBack', models.ImageField(null=True, upload_to='images/aadharBack')),
                ('age', models.CharField(max_length=2, null=True)),
                ('startPoint', models.CharField(max_length=255, null=True)),
                ('endPoint', models.CharField(max_length=255, null=True)),
                ('homeDistrict', models.CharField(max_length=255, null=True)),
                ('depot', models.CharField(max_length=255, null=True)),
                ('rate', models.CharField(max_length=2, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('institution', models.CharField(max_length=255, null=True)),
                ('course', models.CharField(max_length=255, null=True)),
                ('hodApproval', models.IntegerField(default=0, null=True)),
                ('institutionApproval', models.IntegerField(default=0, null=True)),
                ('ksrtcApproval', models.IntegerField(default=0, null=True)),
                ('front', models.ImageField(null=True, upload_to='files/front')),
                ('back', models.ImageField(null=True, upload_to='files/back')),
                ('cost', models.CharField(max_length=255, null=True)),
                ('endDate', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
