# Generated by Django 5.0.4 on 2024-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_concessionform_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionform',
            name='depot',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
