# Generated by Django 5.0.4 on 2024-04-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_concessionform_depot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concessionform',
            old_name='middlePoint1',
            new_name='homeDistrict',
        ),
        migrations.RemoveField(
            model_name='concessionform',
            name='concession',
        ),
        migrations.RemoveField(
            model_name='concessionform',
            name='middlePoint2',
        ),
        migrations.RemoveField(
            model_name='concessionform',
            name='middlePoint3',
        ),
        migrations.AddField(
            model_name='concessionform',
            name='back',
            field=models.ImageField(null=True, upload_to='files/back'),
        ),
        migrations.AddField(
            model_name='concessionform',
            name='front',
            field=models.ImageField(null=True, upload_to='files/front'),
        ),
    ]
