# Generated by Django 5.0.4 on 2024-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('primaryKey', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/photo')),
                ('id', models.ImageField(null=True, upload_to='images/id')),
                ('aadhar', models.CharField(max_length=12, null=True)),
                ('aadharFront', models.ImageField(null=True, upload_to='images/aadharFront')),
                ('aadharBack', models.ImageField(null=True, upload_to='images/aadharBack')),
                ('age', models.CharField(max_length=2, null=True)),
                ('startPoint', models.CharField(max_length=255, null=True)),
                ('endPoint', models.CharField(max_length=255, null=True)),
                ('rate', models.CharField(max_length=2, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('institution', models.CharField(max_length=255, null=True)),
                ('course', models.CharField(max_length=255, null=True)),
                ('front', models.ImageField(null=True, upload_to='files/front')),
                ('back', models.ImageField(null=True, upload_to='files/back')),
                ('cost', models.CharField(max_length=255, null=True)),
                ('endDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255, null=True)),
                ('place', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
