# Generated by Django 5.0.4 on 2024-04-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='depot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concession',
            name='homeDistrict',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
