# Generated by Django 5.0.4 on 2024-04-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0002_concession_depot_concession_homedistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255, null=True)),
                ('depot', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
