# Generated by Django 5.0.4 on 2024-04-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksrtc', '0002_remove_concession_user_concession_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depots',
        ),
    ]
